In [2]:
import tensorflow as tf

##installing command pip install tensorflow as tf

x = tf.ones(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [4]:
x = tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [6]:
#Random tensors

x = tf.random.normal(shape=(3,1) , mean=0 , stddev=1.)
print(x)

tf.Tensor(
[[ 0.33750895]
 [-0.733701  ]
 [ 0.8346589 ]], shape=(3, 1), dtype=float32)


In [7]:
x = tf.random.uniform(shape=(3,1) , minval=0 , maxval = 1)
print(x)

tf.Tensor(
[[0.00521505]
 [0.78875244]
 [0.84627557]], shape=(3, 1), dtype=float32)


In [10]:
import numpy as np
x = np.ones(shape=(2,2))
x[0,0] = 0.
print(x)

[[0. 1.]
 [1. 1.]]


In [12]:
#Creating tensorflow variable

v = tf.Variable(initial_value = tf.random.normal(shape=(3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.9685216],
       [-2.0272224],
       [ 0.4241248]], dtype=float32)>


In [13]:
#Assigning a value to tensorflow

v[0,0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[ 3.       ],
       [-2.0272224],
       [ 0.4241248]], dtype=float32)>

In [16]:
#Using assign_add

v.assign_add(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[ 4.       ],
       [-1.0272224],
       [ 1.4241248]], dtype=float32)>

##Operations on Tensor

In [22]:
a = tf.ones((2,3))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = b + c
# e = tf.matmul(a,b)
e *= d

Gradient tape Api

In [23]:
#lets work with gradient api using gradient api

input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)

#Using GradientTape with constant tensor inputs

In [24]:
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)
gradient = tape.gradient(result, input_const)

#Using nested gradienttapes to compute second-order gradients

In [34]:
#little change in the code

time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time ** 2
        
speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)
       

print("speed:", speed.numpy())
    


speed: 0.0
